# -*- mode: ruby -*-
# vi: set ft=ruby:
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"  # Box for the *control* machine

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"  # Memory for all VMs (unless overridden)
    vb.cpus = "1"    # CPUs for all VMs (unless overridden)
  end

  # Node 1 - Nginx + PHP + Wordpress
  config.vm.define "webserver" do |webserver|
    webserver.vm.hostname = "webserver"
    webserver.vm.network "private_network", ip: "192.168.56.201"
    webserver.vm.network "forwarded_port", guest: 80, host: 8200, auto_correct: true
  end

  # Node 2 - Dataserver
  config.vm.define "dataserver" do |dataserver|
    dataserver.vm.hostname = "dataserver"
    dataserver.vm.network "private_network", ip: "192.168.56.202"
    dataserver.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
  end

  # Controlador Machine
  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.56.200"
  end

  # Provisionador Ansible machines
  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.inventory_path = "ansible/hosts"
    ansible.playbook = "ansible/playbook.yml"
    ansible.become = true
    ansible.verbose = false
    ansible.install = true
  end
end